version: '3.8'

services:
  applicationtrackr:
    build: .
    container_name: applicationtrackr
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - GMAIL_USER=nodagala.joga@gmail.com
      - GMAIL_APP_PASS=hmvq mnix oijf race
      - GOOGLE_SHEET_WEBHOOK_URL=https://script.google.com/macros/s/AKfycbyDnaLbrKcZJYhdAsM3vhTGgfmF-evwZxrDDY0oFuIaTw92andC-Um6NJoXjNOHLJgx/exec
      - HEALTHCHECKS_PING_URL=https://hc-ping.com/757142df-c2b9-4081-9103-ba3aed2ff250
